version: "3"

services:
  goapp:
    build: .
    volumes:
      - .:/app
    ports:
      - "8181:8181"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: orders
    volumes:
      - ./data:/var/lib/postgresql/data
